apiVersion: v1
kind: Service
metadata:
  labels:
    name: doorman-client
  name: doorman-client
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: doorman-client