apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-proportional
          resources:
            limits:
              cpu: 10m
          image: gcr.io/google.com/doorman/prometheus:v0.2
          env:
            - name: KUBERNETES_RO_SERVICE_HOST
              value: localhost
            - name: KUBERNETES_RO_SERVICE_PORT
              value: "9090"
          ports:
            - containerPort: 9090
              name: http