apiVersion: v1
kind: Service
metadata:
  labels:
    name: target
  name: target
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  ports:
    - port: 81
      name: grpc
    - port: 80
      name: http
  selector:
    app: target